### ISSUE TITLE
Expose the nom dependency directly

### ISSUE THREAD

**Issue by Firstyear** [inejge/ldap3#102]
When using lber for the ldap3 server crate I maintain, we needed to have support for when an Incomplete error is returned. To achieve this we needed to manually add nom as a dependency of the same version as lber uses.

To help users of the lber crate it would be good to pub use nom::Err, or just pub use nom in the lber crate to prevent the need for them to "version match" nom + lber.

Thanks!

**Comment by inejge** [comment]
Hmm yes, it seems that `Incomplete` inadvertently went private during the port to nom 7. I prefer the minimal suggested fix (`pub use nom::Err`) so I'm going to use that. Thanks for the report.

**Comment by Firstyear** [comment]
Thanks :)
