### ISSUE TITLE
Add support for unsupported controls

### ISSUE THREAD

**Issue by nitnelave** [inejge/ldap3#110]
We've run into an issue with a client sending extra controls with their request, that we don't care about but fail the query parsing: https://github.com/lldap/lldap/issues/301

Would there be a way to either add support for the controls, or add a "parse with unsupported controls as an extra return" method?

**Comment by inejge** [comment]
This crate constructs LDAP client requests, and doesn't parse them (it parses server responses.) Is your issue related to `ldap3_proto`, perhaps? Anyway, I can't find "Unsupported control oid" anywhere in `lldap` sources, so I can't check.

**Comment by nitnelave** [comment]
Oops, sorry, the `ldap3_proto` crate is in a repo _also_ named `ldap3`, so I got confused.
