### ISSUE TITLE
How to mock server for testing purposes?

### ISSUE THREAD

**Issue by lcmgh** [inejge/ldap3#112]

**Comment by inejge** [comment]
I'm not sure what exactly are you asking about. If you need an LDAP server, there are several to choose from, e.g., OpenLDAP, or 389DS, or Active Directory if you have it in your environment. This crate doesn't have, and while I'm maintaining it, won't have, a mock LDAP server.

**Comment by inejge** [comment]
Closing for lack of feedback.

**Comment by lcmgh** [comment]
Sorry for late feedback. I will watch out for a mock.
