### ISSUE TITLE
Bug? simple_bind does not return error if credentials are wrong

### ISSUE THREAD

**Issue by c-antin** [inejge/ldap3#113]
minimal reproducible example:
```rust
use ldap3::result::Result;
use ldap3::LdapConn;

fn main() -> Result<()> {
    let password = rpassword::read_password().unwrap();
    let mut ldap = LdapConn::new("ldaps://domain.local")?;
    ldap.simple_bind("username@domain.local", &password)?;
    Ok(ldap.unbind()?)
}
```

**Comment by inejge** [comment]
Try:

```rust
ldap.simple_bind("username@domain.local", &password)?.success()?;
```

The first `?` gives you the result of the protocol operation. An error there is usually a problem with I/O. A successful return is an `LdapResult` structure, which you can turn into a `Result` with `success()`. Don't use it blindly, there are situations where a non-zero result code indicates a kind of success.
