### ISSUE TITLE
 Integration for Binary Attributes

### ISSUE THREAD

**Issue by celidur** [inejge/ldap3#124]
We can't create user with a binary attribute like picture, we also can't modify it

**Comment by inejge** [comment]
You can, by supplying `add()` or `modify()` with attribute names and values converted to `&[u8]`. See #35.

**Comment by celidur** [comment]
ok thank you I'll try

**Comment by celidur** [comment]
I've make this:
Mod::Replace(UserAttribute::Picture.as_bytes(), HashSet::from([picture.as_slice()]))

It's defined correctly, but in the attribute, not in the binary attribute in the LDAP.
