### ISSUE TITLE
Bind LDAP with GSSAPI using Kerberos keytab

### ISSUE THREAD

**Issue by mlesin** [inejge/ldap3#128]
Can't find a way to perform bind to ldap using keytab file instead of active user's principal.
For example, using HOSTNAME$@EXAMPLE.COM in Active directory environment instead of username@EXAMPLE.COM
Is there any way of doing this or this is a limitation of cross-krb5 crate?

I can do this if I perform this before running my program
```bash
kinit -k -t /etc/krb5.keytab HOSTNAME\$@EXAMPLE.COM
````
but this breaks kerberos cache file for current user and I'm not sure this is the most correct way of doing this.

**Comment by inejge** [comment]
You can pass __-c__ _cachename_ to `kinit`, and/or use `$KRB5CCNAME` for the default cache. GSSAPI support in the crate is deliberately designed to depend on the environment, and not accept any options.

**Comment by inejge** [comment]
Closing as a combination of WONTFIX and a usage question, with workaround provided.
