### ISSUE TITLE
General documentation issues, 0.7.x

### ISSUE THREAD

**Issue by inejge** [inejge/ldap3#3]
This is the place for genral remarks and discussion about the crate documentation. Issues for specific, localized bugs, such as typos and unclear or ambiguous wording, should be opened separately. Ideally, discussion in this issue should result in opening more targeted issues, which can then be resolved. This message will contain an overview of active sub-issues, and the title should reflect the library version(s) covered.

**Comment by archaelus** [comment]
One question I have about this crate that isn't obvious from the documentation at the moment is whether this library can be used as an LDAP server or proxy (i.e. I see the LDAP client support, but can't tell if there's a way to use this crate to act as an LDAP server - I am interesting in building an LDAP -> Rest API proxy and can't tell from the docs if this crate is what I'm after). 

Clarifying in the documentation whether or not this crate can be or intends to be useable as an LDAP server or proxy would be helpful I think. (ps: thanks! neat crate)

**Comment by inejge** [comment]
@archaelus Thanks for the comment! You're right, there is no explicit mention of the fact that the library is client-only (see #5 for a brief rationale), although the README _is_ titled "LDAP Client Library". I've opened an issue for updating the docs.

**Comment by tjyang** [comment]
Can this issue be closed ?  See https://github.com/inejge/ldap3/blob/master/README.md#ldap-client-library

**Comment by archaelus** [comment]
Yep! Thanks for the documentation update.On Oct 20, 2022, at 06:02, T.J. Yang ***@***.***> wrote:﻿
Can this issue be closed ?  See https://github.com/inejge/ldap3/blob/master/README.md#ldap-client-library

**Comment by tjyang** [comment]
I didn't do the doc update and I can't close this issue. Just a friendly reminder to close out this issue.

**Comment by inejge** [comment]
As noted in the opening post, this issue was meant as a general place to discuss documentation requests/issues, not specifically the one about the client/server/proxy distinction. Nevertheless, for the past five years it elicited precisely one report, which could have been opened independently, so it hasn't been very useful. I'll close it, and any documentation issues may be opened separately.
