### ISSUE TITLE
Support Tokio 0.2

### ISSUE THREAD

**Issue by cetra3** [inejge/ldap3#40]
With async/await & tokio 0.2 released it might be good to refresh this library

**Comment by Geobert** [comment]
If I believe #38 and #29 it's not an easy task and the Author doesn't have the time to do it atm, sadly.

**Comment by Geobert** [comment]
This can be close 🥳

**Comment by inejge** [comment]
Well, yes :slightly_smiling_face: I'll go through the old issues and close accordingly when it all settles down a bit.
