### ISSUE TITLE
Add Rustls support

### ISSUE THREAD

**Issue by Geobert** [inejge/ldap3#43]
Now that the code has been updated to `tokio` 0.2 (thank you again for that!), it should be possible with not too much work to support `rustls` to add an alternative to `native-tls`.

**Comment by inejge** [comment]
Heh, not so fast :wink: Although `rustls` offers similar interfaces through its `tokio` adpater, they're not the same, and the point of the library is to work with as few special cases as possible. So, this can wait. I'll leave it open so it can be noticed.

**Comment by Geobert** [comment]
I'm so happy that this lib is back alive, sorry for my enthusiasm ;)

I'm opening this because we already use tokio-rustls because we want to avoid the `native-tls`. I've seen a PR to add rustls support to `tiny-http` (through `rouille`) and it was small. Hence why I though it's not a so big job to do. Sorry if I'm mistaken :)

**Comment by Geobert** [comment]
Hi @inejge, 

do you mind if I have a look at that?

Regards,

**Comment by inejge** [comment]
I'm preparing to release 0.7 proper, and I'm not going to make potentially destabilizing changes to the code so close to the release. The first stable release is going to be 0.7.1; the earliest I can look into `rustls` support is after that.

**Comment by Geobert** [comment]
Yes sure :) I started the work and put it behind a feature flag, so using native-tls will still be the same
