### ISSUE TITLE
[Question] [0.7-alpha] Why search needs `'static`?

### ISSUE THREAD

**Issue by Geobert** [inejge/ldap3#48]
Hi,

Among the incoming changes with 0.7, I noticed that `LdapConn::search` now needs `'static` lifetime for `attrs`, why is that? Doesn't that make the whole function unusable?

I have an internal test tool that receive the parameters from a script, so my attrs are not `'static` per se even if they live the whole program lifetime. Or maybe (and probably) I'm missing something?

**Comment by inejge** [comment]
`S: 'static` includes owned types like `String`, so you can pass a vector of `String`s as `attrs` (but not a vector of _references_ to `String`s). If you have a vector of `&str`s of unknown provenance, you need to turn it into a vector of `String`s.

**Comment by Geobert** [comment]
I didn't know about `String` being `'static`! Thanks! 

I indeed have a `Vec<&'a str>` because the script AST stays in memory the whole time.

**Comment by inejge** [comment]
I found the way to relax the `'static` bound, so references can be used again in the `attr` vector. It required a bit of fiddling with lifetimes, but so far it seems to work.
