### ISSUE TITLE
Release 0.9.3?

### ISSUE THREAD

**Issue by Geobert** [inejge/ldap3#69]
Hi,

Is there a plan to release 0.9.3? 

I'm asking because we're using a crate mirroring system so our CI can work even if we lose connectivity but this only works with crates from crates.io :)

Regards,

**Comment by inejge** [comment]
Perhaps in a week or so, I have couple of more pressing things to attend to.

**Comment by inejge** [comment]
I've just published 0.9.3, hence closing this.
