### ISSUE TITLE
Establishing a SASL connection on macOS

### ISSUE THREAD

**Issue by harshasrisri** [inejge/ldap3#74]
Hi,

It's okay if this question is out of scope of this crate and you close this issue. I'm hoping to understand working with SASL.

At the moment, I'm using `simple_bind` with username and password. This may not be relevant, but I am working on macOS and can get my AD info using `klist` and authenticate myself using `kinit`. 

How do I use `sasl_external_bind` to achieve the same thing without username and password?

**Comment by inejge** [comment]
You can't, since `sasl_external_bind()` is specialised for the SASL EXTERNAL mechanism. For Kerberos and AD, you'd need GSSAPI, which is something I thought about, but don't plan to support soon.
