### ISSUE TITLE
Utility functions to escape strings

### ISSUE THREAD

**Issue by lawliet89** [inejge/ldap3#8]
Would it be possible to provide a utility module to provide functions for, say, search filters? I am sure there are other stuff that needs escaping, or some sort of special handling.

I [wrote](https://github.com/lawliet89/rowdy/blob/1aeadfce7b701e1277750b7bb24929d191b4b334/src/auth/ldap.rs#L181-L191) something, but I am not even sure if it's correct, because I am not familiar with LADP.

**Comment by inejge** [comment]
Note that escaping is needed only for value literals in the string representation of a filter, but yes, having a utility function for that is a good idea. I'll try add one for the next development release of the library (0.5.x).

What you wrote is correct AFAICS, as it completely captures the UTF1SUBSET production from RFC 4515.

**Comment by lawliet89** [comment]
Right. I am guessing we don't have to worry about invalid UTF-8 for Rust because the strings are guaranteed to be valid UTF-8 and would have error-ed elsewhere.

Thanks.

**Comment by inejge** [comment]
Escaping function added in 5db4c395dfef97a5128d4df36a6b4a255230b561, but I won't close the issue until there's a published version on crates.io.

**Comment by inejge** [comment]
`ldap_escape()` is in 0.5.0, so this issue can be closed.
