### ISSUE TITLE
Can ldap connection reconnect?

### ISSUE THREAD

**Issue by Zerowalker** [inejge/ldap3#81]
From my understanding you can clone the `Ldap` handle and keep reusing the same connection.
In my tests it works fine except if the connection is broken (say the server is unavailable).
Then it will forever fail unless i remake the connection.

So i wonder if it's possible to have it try to reconnect at certain intervals?
That the cloned ldaps will fail during this is expected of course.

Also, does dropping a `Ldap` handle equal an `unbind` for just that one?
cause i noticed if i `unbind` it will (as it says) close the connection which makes any future `Ldap` closed as well,
which kinda makes it "useless" for closing when sharing a connection.

Thanks:)

**Comment by inejge** [comment]
Since the first part is a WONTFIX, and the second a clarification not requiring a documentation update, I'll close this.

**Comment by Zerowalker** [comment]
Ah, it made things a bit clearer.
It just shows that i don't understand how the ldap connection works.

Thanks:)
